require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6.0
  DisabledByDefault: false
  Exclude:
    - '**/vendor/**/*'
    - 'bin/**/*'

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 24

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/AccessModifierDeclarations:
  EnforcedStyle: group

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Performance:
  Exclude:
    - '**/test/**/*'
